# Generated by Django 5.2.12 on 2026-03-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_audit_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='首次登录须修改密码'),
        ),
    ]
