# Generated by Django 5.2.12 on 2026-03-13 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('scrape', '数据抓取'), ('schedule', '定时任务'), ('workflow', '工作流'), ('trigger', '触发器')], default='schedule', max_length=20, verbose_name='任务类型')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置(JSON)')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '运行中'), ('paused', '已暂停'), ('error', '异常')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次运行')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_tasks', to='organizations.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '自动化任务',
                'verbose_name_plural': '自动化任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
