# Generated by Django 5.2.12 on 2026-03-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_backfill_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtask',
            name='task_id',
            field=models.CharField(blank=True, help_text='10位唯一ID，以TASK开头', max_length=10, unique=True, verbose_name='任务ID'),
        ),
    ]
