# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0005_add_audit_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationtask",
            name="description",
            field=models.TextField(blank=True, verbose_name="任务详细说明"),
        ),
        migrations.AddField(
            model_name="automationtask",
            name="schedule_type",
            field=models.CharField(
                choices=[("once", "执行一次"), ("recurring", "周期性执行")],
                default="once",
                max_length=20,
                verbose_name="执行类型",
            ),
        ),
        migrations.AddField(
            model_name="automationtask",
            name="scheduled_run_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="计划执行时间"),
        ),
        migrations.AddField(
            model_name="automationtask",
            name="cron_expression",
            field=models.CharField(
                blank=True,
                help_text="周期性任务使用，如 0 9 * * * 表示每天 9:00",
                max_length=100,
                verbose_name="Cron 表达式",
            ),
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="task_attachments/%Y/%m/%d/", verbose_name="附件")),
                ("remark", models.CharField(blank=True, max_length=200, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="上传时间")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="automation.automationtask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务附件",
                "verbose_name_plural": "任务附件",
            },
        ),
    ]
