# Generated by Django 5.2.12 on 2026-03-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_task_id_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtask',
            name='approval_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '被取消')], default='pending', max_length=20, verbose_name='审批状态'),
        ),
    ]
