# Generated by Django 5.2.12 on 2026-03-14 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_add_approval_cancelled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='备注内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='automation.automationtask', verbose_name='所属任务')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
            ],
            options={
                'verbose_name': '任务备注',
                'verbose_name_plural': '任务备注',
                'ordering': ['-created_at'],
            },
        ),
    ]
