# Generated by Django 5.2.12 on 2026-03-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_add_task_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtask',
            name='approval_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '审批通过'), ('assign_build', '指派人员构建工作'), ('assign_done', '指派任务完成'), ('executable', '任务可执行'), ('rejected', '已驳回'), ('cancelled', '被取消')], default='pending', max_length=20, verbose_name='审批状态'),
        ),
    ]
