# Generated by Django 5.2.12 on 2026-03-14 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_add_approval_workflow_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_build_tasks', to=settings.AUTH_USER_MODEL, verbose_name='指派构建人员'),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='build_status',
            field=models.CharField(blank=True, choices=[('accepted', '接受任务'), ('in_progress', '构建工作进行中'), ('completed', '构建工作完成'), ('return_revision', '退回再修改')], default='', max_length=20, verbose_name='构建状态'),
        ),
    ]
