# Generated by Django 5.2.12 on 2026-03-14 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '编辑'), ('delete', '删除(软删除)'), ('restore', '恢复'), ('approve', '审批通过'), ('reject', '审批驳回'), ('permanent_delete', '永久删除')], max_length=20, verbose_name='操作类型')),
                ('target_model', models.CharField(max_length=50, verbose_name='目标模型')),
                ('target_id', models.PositiveIntegerField(verbose_name='目标ID')),
                ('target_repr', models.CharField(blank=True, max_length=200, verbose_name='目标描述')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
