# Generated by Django 5.2.12 on 2026-03-13 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='组织名称')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='组织编码')),
                ('org_type', models.CharField(choices=[('company', '单公司/单位'), ('group', '集团公司'), ('subsidiary', '分子公司'), ('distributor', '总代理商'), ('sub_distributor', '子代理商')], default='company', max_length=20, verbose_name='组织类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.organization', verbose_name='上级组织')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
                'ordering': ['code'],
            },
        ),
    ]
