# Generated by Django 5.2.12 on 2026-03-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='组织编码'),
        ),
    ]
